<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <WebView2UseWinRT>False</WebView2UseWinRT>
    <WebView2EnableCsWinRTProjection>False</WebView2EnableCsWinRTProjection>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>True</UseWPF>
    <Description>A test application that simulates NG9-1-1 calls from an Originating Service Provider (OSP)</Description>
    <Copyright>2026, Philip Reichl</Copyright>
    <PackageProjectUrl>https://phrsite.github.io/OspSimulator</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PhrSite/OspSimulator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>1.2.0</AssemblyVersion>
    <FileVersion>1.2.0</FileVersion>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>1.2.0 - Various fixes and changes. See VersionHistory.md</PackageReleaseNotes>
    <Version>1.2.0</Version>
    <Authors>philip_reichl@msn.com</Authors>
    <Company>phrsite</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ng911Lib" Version="2.0.1" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="SipLib" Version="1.1.0" />
    <PackageReference Include="SipLib.Audio.Windows" Version="1.1.0" />
    <PackageReference Include="SipLib.Video.Windows" Version="1.1.0" />

  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="AdditionalData\6306820001\PidfLo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820001\ServiceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820001\SubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820001\SubSubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820002\PidfLo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820002\ServiceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820002\SubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820003\PidfLo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820003\ServiceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820003\SubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820004\PidfLo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820004\ServiceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820004\SubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\AutomatedCrashNotification.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\Comment.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\DeviceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\PidfLo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\ProviderInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\ProviderInfo1.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\ProviderInfo2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\ServiceInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AdditionalData\6306820005\SubscriberInfo.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="avcodec-61.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="avdevice-61.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="avfilter-10.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="avformat-61.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="avutil-59.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="OspSimulator.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="OspSimulator.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="postproc-58.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Recordings\DefaultAudioRecording.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="swresample-5.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="swscale-8.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>